use master;
go
ALTER DATABASE Pruebas ADD FILEGROUP Grupo1
go
ALTER DATABASE Pruebas ADD FILEGROUP Grupo2
go
ALTER DATABASE Pruebas ADD FILEGROUP Grupo3
go
ALTER DATABASE Pruebas ADD FILEGROUP Grupo4
go
ALTER DATABASE Pruebas ADD FILEGROUP Grupo5
go

--ALTER DATABASE Pruebas ADD FILEGROUP FgCatalogo
--go