USE Pruebas;
GO

SELECT ID
      ,ORDERDATE
      ,PURCHASEORDERNUMBER
      , $PARTITION.FP_FechasOrdenes(ORDERDATE) AS Particion
  FROM ORDENES
  ORDER BY PARTICION
 
GO
SELECT COUNT(ID) AS FILAS
FROM ORDENES
WHERE ORDERDATE BETWEEN '01/01/2013' AND '12/31/2013'
